project_id = "cxyfwikrjtovvyvcyacl"

[functions.zapi-send-message]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-status]
verify_jwt = false

[functions.ai-responder]
verify_jwt = false

[functions.station-login]
verify_jwt = false
