import { corsHeaders } from "../_shared/cors.ts";

const SYSTEM_PROMPT = `Você é um especialista em análise de conversas de atendimento ao cliente.

Sua tarefa é gerar um resumo CONTEXTUAL e ÚTIL de uma conversa entre uma IA e um cliente, para que um atendente humano possa assumir o atendimento.

O resumo deve incluir:
1. **Assunto principal**: O que o cliente está buscando/precisando
2. **Ponto da conversa**: Onde a conversa parou, qual foi a última interação relevante
3. **Informações coletadas**: Dados importantes mencionados pelo cliente (CEP, produto de interesse, problema relatado, etc)
4. **Próximos passos sugeridos**: O que o atendente humano deve fazer/responder
5. **Tom do cliente**: Se estava satisfeito, frustrado, com dúvidas, etc

Seja CONCISO mas COMPLETO. O resumo deve ter entre 3-5 linhas, máximo 150 palavras.
Use markdown para destaque: **negrito** para pontos importantes.

NÃO liste as mensagens uma a uma. NÃO repita o conteúdo literal das mensagens.
SINTETIZE o contexto e as informações relevantes.

Exemplo de BOM resumo:
"Cliente interessado em **bike gravel** para treinos. Perguntou sobre **frete para CEP 18040-000** e **valor da bike específica modelo X**. IA informou que precisa do valor do produto para calcular frete. Cliente ainda não forneceu essa informação. **Próximo passo**: Perguntar qual modelo específico ele quer e o valor, então calcular o frete. Cliente demonstrou interesse genuíno e está em fase de pesquisa."

Exemplo de MAU resumo:
"Cliente: Fefo boa tarde
IA: Boa tarde! Seja bem-vindo à Fefo Bikes!
Cliente: Tem guidao voador na loja?
IA: Vou verificar"`;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { conversation } = await req.json();

    if (!conversation) {
      return new Response(
        JSON.stringify({ ok: false, error: "missing_conversation" }),
        { 
          status: 400, 
          headers: { ...corsHeaders, "Content-Type": "application/json" } 
        }
      );
    }

    const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY");
    if (!GROQ_API_KEY) {
      console.error("GROQ_API_KEY not configured");
      return new Response(
        JSON.stringify({ ok: false, error: "groq_not_configured" }),
        { 
          status: 500, 
          headers: { ...corsHeaders, "Content-Type": "application/json" } 
        }
      );
    }

    const groqResponse = await fetch(
      "https://api.groq.com/openai/v1/chat/completions",
      {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${GROQ_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            { 
              role: "system", 
              content: SYSTEM_PROMPT 
            },
            { 
              role: "user", 
              content: `Gere um resumo contextual desta conversa:\n\n${conversation}` 
            },
          ],
          max_tokens: 300,
          temperature: 0.3,
        }),
      }
    );

    if (!groqResponse.ok) {
      const errText = await groqResponse.text();
      console.error("Groq API error:", groqResponse.status, errText);
      return new Response(
        JSON.stringify({ ok: false, error: "groq_error" }),
        { 
          status: 500, 
          headers: { ...corsHeaders, "Content-Type": "application/json" } 
        }
      );
    }

    const groqData = await groqResponse.json();
    const summary = groqData.choices?.[0]?.message?.content?.trim();

    if (!summary) {
      console.error("No summary generated by Groq");
      return new Response(
        JSON.stringify({ ok: false, error: "empty_summary" }),
        { 
          status: 500, 
          headers: { ...corsHeaders, "Content-Type": "application/json" } 
        }
      );
    }

    return new Response(
      JSON.stringify({ ok: true, summary }),
      { 
        headers: { ...corsHeaders, "Content-Type": "application/json" } 
      }
    );

  } catch (err) {
    console.error("Generate handoff summary error:", err);
    return new Response(
      JSON.stringify({ ok: false, error: String(err) }),
      { 
        status: 500, 
        headers: { ...corsHeaders, "Content-Type": "application/json" } 
      }
    );
  }
});
