// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxyfwikrjtovvyvcyacl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4eWZ3aWtyanRvdnZ5dmN5YWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMzc2MzYsImV4cCI6MjA4ODcxMzYzNn0.B4JNUOSuxHaMLP45mF780hyuQEzuHge7AMkyT_fBGHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});